---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# cryoCompare

<!-- badges: start -->
<!-- badges: end -->

Comparisons for cryo-ET segmentation and denoising algorithms for BCB410H: Applied Bioinformatics and the Qu Lab.

## Description

cryoCompare is an R package designed to analyse cryo-electron tomography (cryo-ET) data by retrieving tomograms from the CryoET Data Portal and comparing the performance of segmentation and denoising algorithms. It improves current bioinformatics workflows by providing a streamlined, standardised way to access algorithm accuracy and visualise differences across methods, which has not previously been available in R. The package was developed using `R version 4.4.2 (2024-10-31)`, `Platform: aarch64-apple-darwin20`, and `Running under: macOS 26.0.1`. 

cryoCompare was developed as part of the BCB410H: Applied Bioinformatics course at the University of Toronto, and for the Qu Lab at the National University of Singapore.

## Installation

To install the latest version of the package:

``` r
install.packages("devtools")
library("devtools")
devtools::install_github("jeremyschan/cryoCompare", build_vignettes = TRUE)
library("cryoCompare")
```

## Overview



## Contributions



## References
https://cryoetdataportal.czscience.com/datasets/10006?ground_truth=true - for example dataset with ground truth


## Acknowledgements



## Package Structure
